### ISSUE TITLE
Movies release dates off by 100 years

### ISSUE THREAD

**Issue by matc84** [vega/vega-datasets#111]
There are several movies listed in the `movies.json` dataset (everything after 2011) that are listed as having come out 100 years after they were actually released. It's a pretty quick fix and I'm wondering if a pull request would be welcome to either fix the data or create a new dataset with corrected data.

<img width="447" alt="Screen Shot 2019-11-24 at 5 59 43 PM" src="https://user-images.githubusercontent.com/29306639/69506781-f2f9a200-0ee4-11ea-9c86-2ff6419b58b8.png">

**Comment by jheer** [comment]
Thanks! These errors (as well as others, can you find them?) are well known and intentionally included as this dataset is used for instructional purposes, including the need to reckon with dirty data. However, we should probably add a comment to this effect in the

**Comment by matc84** [comment]
Thanks for the quick reply. The other error I found is that the movies in 2011 have budgets listed but no gross (seems like they were recorded in the dataset while production info was available, but before they were released?). Are there other errors? I think a second, corrected dataset or a comment that the dataset has intentional errors would be good.
