### ISSUE TITLE
Add OHLC Data

### ISSUE THREAD

**Issue by eitanlees** [vega/vega-datasets#118]
I think the addition of an "[Open High Low Close](https://en.wikipedia.org/wiki/Open-high-low-close_chart)" dataset would useful.

The VL example [Candlestick Chart](https://vega.github.io/vega-lite/examples/layer_candlestick.html) hard codes data that is found in an earlier Protovis example found [here](https://mbostock.github.io/protovis/ex/candlestick.html) . 

The dataset contains the performance of the Chicago Board Options Exchange [Volatility Index](https://en.wikipedia.org/wiki/VIX) ([VIX](https://finance.yahoo.com/chart/%5EVIX?ltr=1#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJ0aW1lVW5pdCI6bnVsbCwiY2FuZGxlV2lkdGgiOjgsInZvbHVtZVVuZGVybGF5Ijp0cnVlLCJhZGoiOnRydWUsImNyb3NzaGFpciI6dHJ1ZSwiY2hhcnRUeXBlIjoibGluZSIsImV4dGVuZGVkIjpmYWxzZSwibWFya2V0U2Vzc2lvbnMiOnt9LCJhZ2dyZWdhdGlvblR5cGUiOiJvaGxjIiwiY2hhcnRTY2FsZSI6ImxpbmVhciIsInN0dWRpZXMiOnsidm9sIHVuZHIiOnsidHlwZSI6InZvbCB1bmRyIiwiaW5wdXRzIjp7ImlkIjoidm9sIHVuZHIiLCJkaXNwbGF5Ijoidm9sIHVuZHIifSwib3V0cHV0cyI6eyJVcCBWb2x1bWUiOiIjMDBiMDYxIiwiRG93biBWb2x1bWUiOiIjRkYzMzNBIn0sInBhbmVsIjoiY2hhcnQiLCJwYXJhbWV0ZXJzIjp7IndpZHRoRmFjdG9yIjowLjQ1LCJjaGFydE5hbWUiOiJjaGFydCJ9fX0sInBhbmVscyI6eyJjaGFydCI6eyJwZXJjZW50IjoxLCJkaXNwbGF5IjoiXlZJWCIsImNoYXJ0TmFtZSI6ImNoYXJ0IiwidG9wIjowfX0sInNldFNwYW4iOnt9LCJsaW5lV2lkdGgiOjIsInN0cmlwZWRCYWNrZ3JvdWQiOnRydWUsImV2ZW50cyI6dHJ1ZSwiY29sb3IiOiIjMDA4MWYyIiwiZXZlbnRNYXAiOnsiY29ycG9yYXRlIjp7ImRpdnMiOnRydWUsInNwbGl0cyI6dHJ1ZX0sInNpZ0RldiI6e319LCJzeW1ib2xzIjpbeyJzeW1ib2wiOiJeVklYIiwic3ltYm9sT2JqZWN0Ijp7InN5bWJvbCI6Il5WSVgifSwicGVyaW9kaWNpdHkiOjEsImludGVydmFsIjoiZGF5IiwidGltZVVuaXQiOm51bGwsInNldFNwYW4iOnt9fV19)) in the summer of 2009.

I think including this dataset would be especially useful for people in finance. 

Possible names: `vix.json`, `vix-ohlc.json` or just `ohlc.json`?

Let me know what your think and I can put together a PR.

**Comment by domoritz** [comment]
That sounds great. Make sure to also update the sources file in this repo. Would you also want to send a pull request to update the example in the Vega-Lite repo?

**Comment by eitanlees** [comment]
Sure thing. Yeah, I can also update the example once the data is merged.

**Comment by jakevdp** [comment]
Once this is released, we should update vega_datasets and add this as a local dataset.

**Comment by eitanlees** [comment]
yes yes, it's all part of my grand plan to update the candlestick example 🕯📊😀

I am heading home for today, but I will most likely have some time this weekend to integrate everything.

**Comment by domoritz** [comment]
https://github.com/vega/vega-datasets/releases/tag/v1.29.0

**Comment by jakevdp** [comment]
Thanks! I'll try to incorporate this into vega_datasets sometime this weekend, unless @eitanlees beats me to it :grinning:

**Comment by jakevdp** [comment]
vega_datasets 0.8 released:
```
>>> import vega_datasets
>>> vega_datasets.__version__
'0.8.0'
>>> df = vega_datasets.data.ohlc()
>>> df.head()
        date   open   high    low  close signal       ret
0 2009-06-01  28.70  30.05  28.45  30.04  short -4.893964
1 2009-06-02  30.04  30.13  28.30  29.63  short -0.322581
2 2009-06-03  29.62  31.79  29.62  31.02  short  3.686636
3 2009-06-04  31.02  31.02  29.92  30.18  short  4.510109
4 2009-06-05  29.39  30.81  28.85  29.62  short  6.084243
```
