### ISSUE TITLE
Update sf-temps

### ISSUE THREAD

**Issue by eitanlees** [vega/vega-datasets#128]
I figured once the Seattle temperatures are updated (#127) we should also update the corresponding San Francisco temperatures. I've already downloaded the data from the San Francisco International Airport weather station. 

<img width="1007" alt="Screen Shot 2019-12-18 at 10 03 35 AM" src="https://user-images.githubusercontent.com/2041969/71097254-b9335880-217d-11ea-9c53-91db21c76338.png">

Making a note of it here so we don't forget.

**Comment by domoritz** [comment]
I'll wait with the release for this.
