### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by craigcitro** [vega/vega-datasets#13]
Any license info on this repo?

**Comment by domoritz** [comment]
The datasets come from different sources and have different licenses. Please check the original sources for licenses. All scripts are BSD.

**Comment by craigcitro** [comment]
Ah, the edit answers the question I was about to type 😉 A list of sources would be helpful.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-datasets/issues/15

**Comment by craigcitro** [comment]
Awesome. Still worth keeping this open for a top-level `LICENSE` for the code? (If not, feel free to close.)

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega-datasets/commit/34d749afe9a1c733004e6253ee6b6f367e5b856b
