### ISSUE TITLE
missing datasets for vega 3 examples

### ISSUE THREAD

**Issue by mathisonian** [vega/vega-datasets#16]
I'm trying to run the examples specs in latest vega release, but am getting some errors with missing datasets, including `flare-dependencies.json` from https://github.com/vega/vega/blob/master/spec/tree-radial-bundle.vg.json, `normal-2.json` and `flights-200k.json`. Are these available somewhere 

(apologies if this issue is in the wrong spot)

**Comment by domoritz** [comment]
The files are in https://github.com/vega/vega/tree/master/web/data but should be in vega-datasets as well.
