### ISSUE TITLE
Update to 2017 Census

### ISSUE THREAD

**Issue by montyvesselinov** [vega/vega-datasets#171]
Any plans to update us-10m to represent the latest county FIPS.

https://cdn.jsdelivr.net/npm/us-atlas@2/us/10m.json

**Comment by domoritz** [comment]
We could do that. Wanna send a pull request?

**Comment by montyvesselinov** [comment]
Sure! Do you have examples how to convert to vega topo json format somewhere?

**Comment by jheer** [comment]
One thing to keep in mind is what examples and test specifications in Vega and/or Vega-Lite may be using a dataset before we make any updates. Will it break existing test cases? In the case of geo data, might the inclusion of different ids/regions break joins (lookups) with other (also "outdated") data sets?

I'm supportive of moving to more recent examples, just want to make sure we are keeping these downstream effects in mind. Thanks!

**Comment by jwoLondon** [comment]
Perhaps timestamp the file names (`us10m_2017.json` etc.).

**Comment by montyvesselinov** [comment]
Yes, it will be better to call it us10m_2017.json. The FIPS change regularly.

Do you have an example how to convert?

**Comment by domoritz** [comment]
I’d prefer not to have multiple versions of the same data unless it causes issues with the existing examples.

**Comment by domoritz** [comment]
@montyvesselinov I want to cut a 2.0 release and include this update. I think the only way forward is to also include an updates unemployment dataset (and include a year such as `unemployment_2017.csv`. Can you send a pull request in the next few days?

**Comment by domoritz** [comment]
Closing as we are moving to v2 now.
