### ISSUE TITLE
cars.json contains invalid data

### ISSUE THREAD

**Issue by arvind** [vega/vega-datasets#2]
It appears that some invalid data has crept into `cars.json`. Presumably, this is to highlight Voyager functionality, but it's had the knock-on effect of producing erroneous output with the Vega examples:

![Cars Parallel Coords](http://i.imgur.com/9N6NhLf.jpg)

Perhaps `cars.json` should contain the clean values, and a secondary duplicate data file introduces the error? **Note:** I believe this error was also introduced to the Vega test cases, so we'll want to update that too.

**Comment by kanitw** [comment]
We did not add additional error data.  Actually, we try to even clean it more.  
Basically, we replace `-1` (which the way to encapsulate `null` in the original data) with `null`.

We certainly can create two versions of `cars.json` but I wonder if you really want `-1` on the scale for this example.  I think this might be a good example for supporting a hybrid scale that can display null value in the future?

**Comment by kanitw** [comment]
Just another idea -- this could be an example for demoing "impute" transform as well.

**Comment by arvind** [comment]
Thanks, I had never noticed the invalid tuples in the parallel coordinates example before! I opted to fix the rendering issue by just filtering out the invalid tuples (vega/vega@c282e06 and vega/vega-editor@6cc9f96).
