### ISSUE TITLE
Some files have ^M (carriage return) at end of each line. It should be consistent

### ISSUE THREAD

**Issue by ydlamba** [vega/vega-datasets#30]
There are only 5 such files. I think one should remove these specials characters.

**Comment by ydlamba** [comment]
When we run `yarn vendor` in `editor`. Git shows few modified files which are because of this issue.
![image](https://user-images.githubusercontent.com/21237466/36952621-6383d92a-2038-11e8-9d43-47818ae7cf49.png)
![image](https://user-images.githubusercontent.com/21237466/36952630-8401978c-2038-11e8-98c5-38c52e5acf28.png)

**Comment by domoritz** [comment]
This has bugged me for a while but never got around to fixing it. Thanks @ydlamba!
