### ISSUE TITLE
Are you open to including more datasets?

### ISSUE THREAD

**Issue by palewire** [vega/vega-datasets#33]
I work in data journalism and I think it would be cool to include some simple but famous datasets from our profession in your examples. If I submitted some would you be open to considering them?

**Comment by domoritz** [comment]
Yes, we would definitely consider them. Ideally, you could also submit a corresponding visualization to https://vega.github.io/vega-lite/examples/ or https://vega.github.io/vega/examples/. What datasets do you have in mind?

**Comment by palewire** [comment]
I have not compiled an complete list, but off the top of my head things that I think would be useful to people in my field but also broadly applicable include:

- Past presidential election results by county or state
- Political polling data for an individual race
- Activity tied to individual politicians, like votes
- Lists of people tied to locations (perhaps all the homicides in a city like Los Angeles with the place of death)
- Lists of people or organizations with financial values associated (i.e. baseball player salaries or spending in U.S. government departments)
- Award-winning and famous work in our field that have released their data as open source and could serve as inspirational when used in training examples

**Comment by domoritz** [comment]
These sound like super interesting datasets. To demonstrate the utility of these datasets for visualization, I'd like to have a corresponding Vega or Vega-Lite chart.

**Comment by palewire** [comment]
Excellent. You'll hear from me again before too long.

**Comment by kanitw** [comment]
I'd be careful about adding new datasets, especially if they are very large as we don't want to make dependencies download for our development be too slow.

**Comment by palewire** [comment]
@kanitw I agree that any new files should be strictly limited in size.

**Comment by domoritz** [comment]
So yes, we are open to accepting new datasets.
