### ISSUE TITLE
Can not load earthquakes dataset

### ISSUE THREAD

**Issue by aParsecFromFuture** [vega/vega-datasets#348]
I couldn't load the earthquakes dataset, then i tried to manually download the json file and tried to read with pandas, the same error occured.

![Screenshot 2022-02-19 163946](https://user-images.githubusercontent.com/30957924/154803211-8649a92b-5429-4918-adbe-235763ddccfc.png)

**Comment by domoritz** [comment]
This error is for the Python package which doesn't have the same datasets. 

https://github.com/altair-viz/vega_datasets
