### ISSUE TITLE
Add volcano.json 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-datasets#38]
https://github.com/vega/vega/blob/master/docs/data/volcano.json is used by Vega examples and we can only build examples in the editor if the datasets are in vega-datasets. 

What's the source if this dataset? Is there a cleaner version that doesn't have the specific format that works well for just Vega?

**Comment by jheer** [comment]
I got the volcano data from [d3-contour](https://github.com/d3/d3-contour). The original source is R: https://www.rdocumentation.org/packages/datasets/versions/3.5.0/topics/volcano

I'm not sure what you want in a "cleaner" version. The version currently used is pretty darn minimal and makes sense for a raster grid (as opposed to tabular data). It's the format that d3-contour expects for gridded values.

**Comment by domoritz** [comment]
I guess I would like to have a table with `x`, `y`, and `height`. The dataset would make more sense for tools like Vega-Lite and Altair.

**Comment by jheer** [comment]
My only reason for including this dataset is to demonstrate and test the use of contours with pre-gridded data. For this, [d3-contour](https://github.com/d3/d3-contour#_contours) requires an array of numeric values as input. So one way or another (raw or transformed), I need that format.

**Comment by domoritz** [comment]
Should we inline the data then?

**Comment by jheer** [comment]
Are you suggesting that we remove the separate volcano.json data file and instead put the data directly in the example spec? If so, I don't have any major objections.

**Comment by jheer** [comment]
OK, the new volcano examples with inline data have been pushed to master on both vega and vega-lib. The corresponding volcano.json file has been deleted.
