### ISSUE TITLE
build/vega-datasets.min.js is now an iife, breaking require

### ISSUE THREAD

**Issue by mbostock** [vega/vega-datasets#391]
I noticed that #388 changed build/vega-datasets.min.js to be an IIFE:

https://github.com/vega/vega-datasets/blob/b2c5de03f7c8055ce544fe9e511710b22263c4c0/rollup.config.js#L40-L46

Whereas build/vega-datasets.js is still a UMD:

https://github.com/vega/vega-datasets/blob/b2c5de03f7c8055ce544fe9e511710b22263c4c0/rollup.config.js#L34-L39

The problem is that `require("vega-datasets")` on Observable will use your unpkg/jsdelivr entry point which points to the IIFE, and thus errors:

https://github.com/vega/vega-datasets/blob/b2c5de03f7c8055ce544fe9e511710b22263c4c0/package.json#L8-L9

You can see it breaking here:

https://observablehq.com/@vega/vega-lite-input-binding

If you want to drop UMD support, we could fix that notebook (and presumably others) by using ES import instead of require:

```js
world = (await import('vega-datasets')).default['world-110m.json'].url
```

But if you are supporting IIFE, maybe it’s worth continuing to support UMD for backwards compatibility?

**Comment by domoritz** [comment]
Thanks for the note. I'll switch back to umd.

**Comment by mbostock** [comment]
Thanks for working on these issues Dominik!
