### ISSUE TITLE
Published build artifacts have the wrong version (2.5.0 instead of 2.5.1)

### ISSUE THREAD

**Issue by mbostock** [vega/vega-datasets#392]
Looks like 2.5.1 #390 includes the wrong version 2.5.0 in the published artifacts. Search for “version” here:

https://cdn.jsdelivr.net/npm/vega-datasets@2.5.1/build/vega-datasets.module.js

This results in broken URLs that point to 2.5.0, which is missing data. For example, this:

```js
world = (await import('vega-datasets@2.5.1')).default['world-110m.json'].url
```

https://cdn.jsdelivr.net/npm/vega-datasets@2.5.0/data/world-110m.json

**Comment by domoritz** [comment]
@hydrosquall I think this is happening because of the auto publishing. Do you have an idea how we can fix this?

This is still a problem in 2.5.2: https://cdn.jsdelivr.net/npm/vega-datasets@2.5.2/build/vega-datasets.module.js

**Comment by domoritz** [comment]
Also, https://cdn.jsdelivr.net/npm/vega-datasets@2.5.3 has version 2.5.2 in it.

**Comment by domoritz** [comment]
Vega-Lite is also broken: https://cdn.jsdelivr.net/npm/vega-lite@5.5.0/build/vega-lite.js has version 5.2.0.

**Comment by hydrosquall** [comment]
Yes, this is the same issue affecting vega-lite reported here

https://github.com/vega/vega-lite/issues/8370

Unfortunately all 3 repos are affected by the same bug:

https://github.com/intuit/auto/issues/2047

It looks like the version is bumped *after* publishing, and the bumps from
the stable branch don’t propagate back to the next branch.

I haven’t gotten a clear answer on what to do about this from the auto
end.  Haven’t been working on build systems recently but am debating
between making a plugin to fix it, or switching to a more actively
maintained project (the two original maintainers of auto no longer work for
intuit, which may have made it harder to support this library)

**Comment by domoritz** [comment]
Switched to release-it. The version is correct as of 2.5.4: https://cdn.jsdelivr.net/npm/vega-datasets@2.5.4/build/vega-datasets.module.js.
