### ISSUE TITLE
Seattle temperature data incorrect?

### ISSUE THREAD

**Issue by jakevdp** [vega/vega-datasets#42]
The ``seattle-temps`` dataset claims that the temperature in Seattle never rose above 76 degrees F in 2010: 

![visualization 48](https://user-images.githubusercontent.com/781659/44621142-c83e1b00-a855-11e8-9c73-76d7d9572348.png)

[Vega Editor Link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSBXATgGxSgAt54AHAZ2QHpqA3AUwHNYA6JgS3iKwCNWOAe3rNYAWjiIKDeBWqTY1aQnh4GY+AwC2lVgGMKdSABpwGSADNBOLQkLBI8AJ5kGhSAaMBfM19OZbHABrd1gcBiR-KAYAOz1BaA4YpnszTAAPe0cXN1RHbTJrWAJjKAsOBjxod0k3UscOLQYAVRiudycIm0EY7lrIPzSoJyznV3cARyxYXq4EDkYTKFgmJnCWTXctJKXLCqr3TR0BqMwnACZRnMnp2cR4Bbrl1fWEXKhbTPryyuq8o7IA18UUgAHcONBuIQAGwABlhIIAJBQ9ERtEg8iRyFRaIwWOwuDx+EIlKj0SIWGI8FwGPRzqxoaxYawAFYUHomMweHrlFKoYA+LxAA)

According to my own memory,  the temperature was much hotter. Other more reliable sources agree; for example, weather underground claims that Seattle hit 96 degrees F in August 2010: https://www.wunderground.com/history/monthly/us/wa/seattle/KSEA/date/2010-8

Perhaps the dataset is mislabeled?

**Comment by domoritz** [comment]
Ping @arvind. Let's make sure to credit the source of this dataset or update it with data from noaa.

**Comment by RandomFractals** [comment]
yeah, we might need to list || ref all your raw data sources ... #15 

I've looked at all of them over a span of a year playing with vega specs & Seattle temps is not the only questionable dataset ...

**Comment by eitanlees** [comment]
I think I figured this issue out!

The numbers aren't direct temperature measures but rather 30 year averages.

From [NOAA Hourly Normal Documentation](https://www1.ncdc.noaa.gov/pub/data/cdo/documentation/NORMAL_HLY_documentation.pdf)

>The 1981-2010 Normals comprise all climate normals using the thirty year period of temperature,degree days, precipitation, snowfall, snow depth, wind, etc. Data is organized into hourly, daily,monthly, seasonal and annual normals. This document describes the elements and layout of the Hourly Normals which are derived from a composite of climate records from numerous sources that were merged and then subjected to a suite of quality assurance reviews.

>The hourly normals provide a suite of descriptive statistics based on hourly observations at a few hundred stations from across the United States and its Pacific territories. Statistics are provided as 30-year averages, frequencies of occurrence, and percentiles for each hour and day of the year. These products are useful in examination of the diurnal change of a particular variable.

I downloaded the data for the Seattle Tacoma International Airport station. 

<img width="779" alt="Screen Shot 2019-12-16 at 7 57 33 PM" src="https://user-images.githubusercontent.com/2041969/70955344-8171c700-203e-11ea-9c08-20959455f9bb.png">

The numbers are a little different from the dataset originally uploaded here. They are similar though!  

I could clean up this new data and replace the current `seattle-temps` if you think that would be useful.

**Comment by domoritz** [comment]
Thank you. I think that having data with clear provenance would be good. @arvind are you okay with updating the dataset?

@eitanlees Thank you for your efforts to update the datasets in this repo. Let me add you as a collaborator.

**Comment by arvind** [comment]
Sounds good to me as I don’t remember the original provenance! Thanks @eitanlees!

**Comment by domoritz** [comment]
Excellent. @eitanlees can you send a pull request?
