### ISSUE TITLE
7 datasets that cannot be loaded

### ISSUE THREAD

**Issue by serg-razum-off** [vega/vega-datasets#438]
**Description**
Hello, Vega team!

I hope you are doing well. I came across an issue while exploring datasets in the Vega dataset repository. Specifically, I found that 7 datasets in the following directory cannot be loaded using the pd.read_json(url) method:

https://github.com/vega/vega-datasets/tree/main/data

I would greatly appreciate it if you could take a look at this issue and provide a possible solution. If you need any additional information from me, please let me know.

Thank you for your time and attention!

**Steps to Reproduce**
Go to https://github.com/vega/vega-datasets/tree/main/data
Select any of the following 7 datasets:
https://raw.githubusercontent.com/vega/vega-datasets/main/data/annual-precip.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/earthquakes.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/londonBoroughs.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/londonTubeLines.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/miserables.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/us-10m.json
https://raw.githubusercontent.com/vega/vega-datasets/main/data/world-110m.json

Load the dataset using pd.read_json(url) method.
Observe that the dataset cannot be loaded.

**Expected behavior**
The datasets in the aforementioned directory should be able to be loaded using pd.read_json(url) method.

**Actual behavior**
7 of the datasets in the directory cannot be loaded using pd.read_json(url) method.

**Additional Information**
Operating System: Windows
Python version: 3.10.9
Pandas version: 1.5.2

list of Erorrs received:
[['ValueError', 'All arrays must be of the same length'],
 ['ValueError', 'All arrays must be of the same length'],
 ['ValueError', 'All arrays must be of the same length'],
 ['ValueError', 'All arrays must be of the same length'],
 ['ValueError', 'All arrays must be of the same length'],
 ['ValueError',
  'Mixing dicts with non-Series may lead to ambiguous ordering.'],
 ['ValueError',
  'Mixing dicts with non-Series may lead to ambiguous ordering.']]

**Comment by domoritz** [comment]
These datasets are not simple tables and therefore cannot be read by pandas. Instead, you need to read them as raw JSON.
