### ISSUE TITLE
What is the source of wheat.json?

### ISSUE THREAD

**Issue by palewire** [vega/vega-datasets#46]
I'm finding it useful for creating simple bar chart examples in Altair. I'm interested to learn more about where the data comes from.

**Comment by domoritz** [comment]
@jheer, do you know?

**Comment by jheer** [comment]
We first used that dataset in the Protovis project: http://mbostock.github.io/protovis/ex/wheat.html

I believe Mike Bostock gathered it. I don't recall if he downloaded it from an online source or transcribed the values manually. In any case, William Playfair is the original source.

From the Protovis page: Often credited as the founder of statistical graphics, William Playfair published this elegant chart in 1822 in a letter to Parliament. It shows 250 years of the price of wheat, typical weekly wages, and the reigning monarch. He intended to demonstrate that “never at any former period was wheat so cheap, in proportion to mechanical labour, as it is at the present time.”

**Comment by palewire** [comment]
I love that it's Playfair data. Is that description of its vintage verified enough to merit including it in the sources file here? I'd be happy to add it.
