### ISSUE TITLE
Unable to process .arrow file in the datasets

### ISSUE THREAD

**Issue by ramses-lee** [vega/vega-datasets#545]
A general demonstration is outlined here in the google collar file: https://colab.research.google.com/drive/1oKhivD5T9Yi1gMl0_7dUwqVFqiNfD43k?usp=sharing

The 'flights-200k.arrow" is producing an error every time I tried to read in the file using Pandas package.

**Comment by domoritz** [comment]
Can you try reading it as a file and stream? Maybe try pyarrow directly.

**Comment by domoritz** [comment]
Ahh, I fixed it. The file wasn't closed properly. 

This works now. 

```py
import pyarrow as pa

with open('data/flights-200k.arrow', 'rb') as f:
    buf = f.read()

    with pa.ipc.open_file(buf) as reader:
        df = reader.read_pandas()

        print(df)
```
