### ISSUE TITLE
`flights-3m` on `v2.10.0` exceeds configured limit

### ISSUE THREAD

**Issue by dangotbanned** [vega/vega-datasets#627]
In https://github.com/vega/altair/pull/3631 I'm working on a new wrapper to this repo in `altair`.

After updating `v2.9.0` -> `v2.10.0`, I'm seeing an error for `flights-3m` only:

> File size exceeded the configured limit of 50 MB.

Reading through [jsdelivr-restrictions](https://github.com/jsdelivr/jsdelivr?tab=readme-ov-file#restrictions), it looks like the default was  raised from **20MB** -> **50MB**.
However `flights-3m` has [increased](https://cdn.jsdelivr.net/npm/vega-datasets@v2.10.0/data/) to  **69.42MB**.

# Related
- https://cdn.jsdelivr.net/npm/vega-datasets@v2.10.0/data/flights-3m.csv
- https://cdn.jsdelivr.net/npm/vega-datasets@v2.9.0/data/flights-3m.csv
- #607

**Comment by domoritz** [comment]
Can you ignore the file? It can't be much smaller if it contains all 3m flights.

**Comment by dangotbanned** [comment]
> Can you ignore the file? It can't be much smaller if it contains all 3m flights.

@domoritz yeah for now, that is essentially what I'm doing.

But unless I'm missing something, the dataset itself isn't accesible via the cdn.

https://cdn.jsdelivr.net/npm/vega-datasets@v2.10.0/data/flights-3m.csv

![Image](https://github.com/user-attachments/assets/88c38741-8a5c-4f56-8a70-670b07434e9c)

**Comment by domoritz** [comment]
Yeah, we could switch to parquet.

**Comment by dangotbanned** [comment]
> Yeah, we could switch to parquet.

Strong agree @domoritz 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QUOQFtMKEPMUBaABwBGAGzG55gOwsARmHmG2AFgsBWC2wCcAJjp1jMF31rbxgQGRA1OQAnAGtlQgBPAAdNZBBraLDuTChIOhIkVB4AGwgo5XhMYrotSlIYeAAPEG5ElK0oCDUSOWKskGaiyurauAAvTAACAAo1awBKFpA21JAAR1I5IjhFYjRNcISKrBG0+GLMAH1VDSXKMvE05tbk1c7u1T7pbgASSjBGJhIloxIQkpRkAB6SH7BByAB0CB2jFI1nhcAgkP+gMiMMwcN0xR2mBhLnhXjY8MM8IAVvcoEsdHJKJhCJRlEyDCYzJYbHY5A5nG5PD4-AEgiEUABtUDnK43VYwIkIMSUXQsNR3epNLTwsCUNB3cZTWYLFDGDzwxyGCkuFxsQx24wsDzGGSyuAXa7qRXK1XqtSXOiYJUKTTcOoNOCDEDwuRoKIQI0TGZzRbILwsK1sFyZlgsfQsQwWfQWQzukBy723M5+tkBy7FMaOLVRmNxqKJ3AR42ps3IFjGeGF9gOYxWXNeDwuCtVhVaJWiesa650OnQVs6tK0+nJk1plBeTPwjxsCxeYX6Dglm2zz3yn0LutqleUVRJJJHCPa6O6+OJvc+3TFgvHJYxDFPFxxwdUwYLvL151rJcX0DUhci6JIokwSgWRqb82z-TsIG7EBKF7U10xMSlrQ4U9HEcYxnC8Yt4IfGtK2fBsxkoQg6F0QxN1-bckmiDZWUAiiUBteFjHtYs2BA4xMynctOA9BDHyQlVl0DbjeP4thBPbESojE8QexTSTkGktxDBdCwbxYc8z1Y6tfWQrieL44sjN1EyzIkg9rNA+0S28Yw2H0RiLxLVzEI4jyVz0vij184TRNIcSLP3ftpMcNx2FLC0jwiixHDizSEu0lDLmStLY2iLtAv7CkqSi3MlI8fRJ2nSQAF1pCAA)

![Image](https://github.com/user-attachments/assets/9353e244-509e-47a4-876a-7e17bfb0db2d)

**Comment by dsmedia** [comment]
@domoritz should I open a PR to save flights-3m as a parquet file (and update flights.py)?

**Comment by domoritz** [comment]
that would be great, thanks!

**Comment by dangotbanned** [comment]
Thanks @domoritz, @dsmedia for such a quick response!

This might be better served by a separate issue.
But more broadly adding `.parquet` variants of the datasets would have benefits *beyond* reducing the file size.

You'd also have:
- Stronger guarantees on data types being interpreted correctly
- Possible support for [general lazy operations](https://docs.pola.rs/user-guide/io/parquet/#scan) or [predicate pushdown](https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html#pandas-read-parquet)
	- I'd find these quite handy to use in (https://github.com/vega/altair/pull/3631)
		- [`polars.read_parquet_schema`](https://docs.pola.rs/api/python/stable/reference/api/polars.read_parquet_schema.html)
		- [`polars.LazyFrame.collect_schema`](https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.collect_schema.html)


If you decided to go down this route, [altair#3631-...metadata.parquet](https://github.com/vega/altair/blob/88d449154edc733e2b7ea682e28dd9eeb4a09b40/altair/datasets/_metadata/metadata.parquet) may be helpful in selecting other candidates for a `.parquet` variant

**Comment by domoritz** [comment]
I agree that parquet is generally better for the reasons you mentioned but csv and JSON are still common, can be read with a text editor, and require parsing which is instructional. Since these datasets are designed for examples, teaching, and demos I think it's useful for them to be what they are.

**Comment by domoritz** [comment]
It would increase the size of the npm package. I don't see many people asking for parquet right now so I'd say let's not do it right now.

**Comment by dangotbanned** [comment]
@dsmedia @domoritz thank you both for this.

All working now and very quickly I might add 🎉 

![Image](https://github.com/user-attachments/assets/89d83795-a6db-4631-98a6-d7475c0c53a0)

**Comment by dangotbanned** [comment]
**I'm happy to open a new issue for this**

In the screenshot from https://github.com/vega/vega-datasets/issues/627#issuecomment-2480823441, you can observe a datetime represented in `"MMDDHHMM"` format.

After reading through #626, I see that this is one of 3 options:

<details><summary>Format options</summary>
<p>

> ### New Generation Script
> 
> _New file: `flights.py`_
> 
> A comprehensive tool for processing U.S. DOT (BTS) On-Time Flight Performance data with enhanced flexibility and features. Creates date formats used in this repo.
> #### Output Format Options
> | Format | Example | Description |
> |--------|---------|-------------|
> | **MMDDHHMM** | **`06142330`** | **June 14, 23:30** |
> | ISO | `2023/06/14 23:30` | ISO-style datetime |
> | Decimal | `23.75` | 23:45 in decimal form |


</p>
</details> 

I've done some work looking into the cost of storing the column as a datetime (not a formatted string)

<details><summary>Conversion</summary>
<p>

```py

import polars as pl
from altair.datasets import Loader

data = Loader.with_backend("polars")
flights: pl.LazyFrame = data("flights-3m", tag="v2.11.0").lazy()

# NOTE: Assuming year is `2001`
date_conv: pl.Expr = (
    pl.concat_str(pl.lit("01"), "date").str.to_datetime("%y%m%d%H%M").alias("date")
)
delay_conv: pl.Expr = pl.duration(minutes=pl.col("delay")).alias("delay")

flights_date: pl.DataFrame = flights.with_columns(date_conv).collect()
flights_date_delay: pl.DataFrame = flights.with_columns(date_conv, delay_conv).collect()

```

</p>
</details> 

<details><summary>Size comparison</summary>
<p>

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QUOQFtMKEPMUBaNgFYDAIxgsALACY2LABwB2O3ICMYYwE4HxzG7mYDMLZgYCAyIGpyAE4A1sqEAJ4ADprIIIkQJOLclHAAXikAbFwghBAQADbEiSiEkaSYYZhQkHQkSKg85RCRyvCY5XRaCcl0AASQ5aRqUJQg3OWYCE2DHeVy3uUAYrwAynkpzubc3VhEWsYQhKVqodzDKSoQaiRy5bcgAB7Kch9ws6vrfrbIh7fIoQ5hPoDLQ5fKjAAUamMAEo5iBKGBXilQHQnnISCgANrOZycZwGAC6YXuWgAjqQ5EQ4IpiGhNGF4t9fv9QGsNsDCKCDkcSsyFgBBcqIKBaBYwLKiwgSqAIBYoYrEJWYAAaKF05gMdzFmAAmnqSdwEJF6DU6pgjVqtLlKIQxpA1IlIphKDloKMFmy3pCsNDUu7Pd7fVAAPoB-poyjdcSpOjesDLNpommpbqtVRBsKMEQIMTKF2YarIdhhRJRdT-QmgVQaLS1yLqaMsdwJ-o+ZOgbMgTKYSJoV5opotNoNz4gKncYwkFbozELWaSCkOtUdQiYD7JkAwKUlwiUXQsNQAOjb9MwCte0tlmHlaMZYEY3RhikiCpgu324LmGEAAkGJFhEWhiIQiSUMgAD0cFsggciXggzKMKQxiXnAEBwWBmARIhixyLoUq7ohBiXtYl7OJeABWiYyrIChyJQd48toLH6EYpgWNYdiOLYLhuJ49jeL4-iBMERIDkkmBuhUUwzFoOiYAA1Kmayctw4Zej6OExnGbzIKS6L7AiSKoiZ5iXuY7gGAUBjmM4bAFIcbDOCw9gyLJIzjIp0z-Jxu4af0cjaTwHp6VGsaYIG4LFLCmAWSi4IsJeBTmCwlgFPZdgOO4XYGD5JRyQpkyBSpCjqZp4VorpkYGbF8UmfY2TmYiqUmel5JeQYnmOJY7guc4BQlfc5VKUFqmhVp9VPBG+nQM18bIJYljtXCnVWZ5NH2EY5j7e47j2O4ljmLY41lf5FXKSm1XzVFjXLUZ4Kbcl21pZeAksEYthsOYgMsCwY2cL58k3VNVW7o9i0xa9JmJR1lngpYl4nfYtjOLYF3uGw9iHfjV1+RMUP3TDOkLdFTUI84bVmVtKMmWjw0AwY9huS5thdjjxMQ6TlXk5olNPUthlxat63vSlO1o7YBTWC59kGFjhiHXzk2CyAxiscLkVwzTEvGaZSUy6jGUGB59g2DlljZcNGuQ1rOtsbD1MvUbCXS59zOXuznkY1jXnWN5YOlSTAV3drutu894stXT3tM84aOW5jZ1FPLVjs5dYcTU7Ucu3rDViytxlSwzH3J2jBqOGwDi5etRQExu0hAA)

![Image](https://github.com/user-attachments/assets/9e15eb40-e64d-44cb-a0c9-23154a81dfa8)

</p>
</details> 


<details><summary><code>python</code> library support</summary>
<p>



`polars`

```
shape: (3_000_000, 5)
┌─────────────────────┬──────────────┬──────────┬────────┬─────────────┐
│ date                ┆ delay        ┆ distance ┆ origin ┆ destination │
│ ---                 ┆ ---          ┆ ---      ┆ ---    ┆ ---         │
│ datetime[μs]        ┆ duration[μs] ┆ i64      ┆ str    ┆ str         │
╞═════════════════════╪══════════════╪══════════╪════════╪═════════════╡
│ 2001-01-01 00:01:00 ┆ -13m         ┆ 2345     ┆ ANC    ┆ LAX         │
│ 2001-01-01 00:03:00 ┆ -20m         ┆ 1946     ┆ LAX    ┆ ATL         │
│ 2001-01-01 00:10:00 ┆ 0µs          ┆ 1671     ┆ PHX    ┆ DTW         │
│ 2001-01-01 00:20:00 ┆ 10m          ┆ 1709     ┆ SEA    ┆ STL         │
│ 2001-01-01 00:22:00 ┆ -13m         ┆ 1736     ┆ SFO    ┆ STL         │
│ …                   ┆ …            ┆ …        ┆ …      ┆ …           │
│ 2001-06-30 23:58:00 ┆ 30m          ┆ 215      ┆ ATL    ┆ SAV         │
│ 2001-06-30 23:59:00 ┆ 1h 27m       ┆ 496      ┆ PIT    ┆ BOS         │
│ 2001-06-30 23:59:00 ┆ 9m           ┆ 151      ┆ ATL    ┆ HSV         │
│ 2001-06-30 23:59:00 ┆ 1h 23m       ┆ 641      ┆ DFW    ┆ DEN         │
│ 2001-06-30 23:59:00 ┆ 16m          ┆ 594      ┆ ATL    ┆ DTW         │
└─────────────────────┴──────────────┴──────────┴────────┴─────────────┘
```

`pandas`

```
                       date             delay  distance origin destination
0       2001-01-01 00:01:00 -1 days +23:47:00      2345    ANC         LAX
1       2001-01-01 00:03:00 -1 days +23:40:00      1946    LAX         ATL
2       2001-01-01 00:10:00   0 days 00:00:00      1671    PHX         DTW
3       2001-01-01 00:20:00   0 days 00:10:00      1709    SEA         STL
4       2001-01-01 00:22:00 -1 days +23:47:00      1736    SFO         STL
...                     ...               ...       ...    ...         ...
2999995 2001-06-30 23:58:00   0 days 00:30:00       215    ATL         SAV
2999996 2001-06-30 23:59:00   0 days 01:27:00       496    PIT         BOS
2999997 2001-06-30 23:59:00   0 days 00:09:00       151    ATL         HSV
2999998 2001-06-30 23:59:00   0 days 01:23:00       641    DFW         DEN
2999999 2001-06-30 23:59:00   0 days 00:16:00       594    ATL         DTW

[3000000 rows x 5 columns]
```

`pyarrow`

```
pyarrow.Table
date: timestamp[us]
delay: duration[us]
distance: int64
origin: large_string
destination: large_string
----
date: [[2001-01-01 00:01:00.000000,2001-01-01 00:03:00.000000,2001-01-01 00:10:00.000000,2001-01-01 00:20:00.000000,2001-01-01 00:22:00.000000,...,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000],[2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,2001-01-09 06:22:00.000000,...,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000,2001-01-16 22:49:00.000000],...,[2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,2001-06-22 15:10:00.000000,...,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000],[2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,2001-06-30 10:47:00.000000,...,2001-06-30 23:58:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000,2001-06-30 23:59:00.000000]]
delay: [[-780000000,-1200000000,0,600000000,-780000000,...,-240000000,480000000,1380000000,720000000,-420000000],[-180000000,1320000000,720000000,600000000,480000000,...,-240000000,-1020000000,-2700000000,-540000000,-1080000000],...,[2220000000,960000000,360000000,240000000,-240000000,...,240000000,-360000000,360000000,360000000,360000000],[-600000000,-300000000,-660000000,-660000000,-360000000,...,1800000000,5220000000,540000000,4980000000,960000000]]
distance: [[2345,1946,1671,1709,1736,...,469,621,581,1679,324],[177,383,813,432,594,...,116,1865,1750,1750,1900],...,[1557,354,317,248,104,...,594,1024,1121,2329,867],[834,813,810,1972,200,...,215,496,151,641,594]]
origin: [["ANC","LAX","PHX","SEA","SFO",...,"IAH","ORD","ATL","SMF","GPT"],["TYS","BTR","PHL","DFW","ORD",...,"CVG","SAN","DTW","LAS","LAX"],...,["PHL","DFW","MKE","SAT","SHV",...,"ATL","EWR","BOS","LAX","ORD"],["MCO","STL","CVG","MIA","BNA",...,"ATL","PIT","ATL","DFW","ATL"]]
destination: [["LAX","ATL","DTW","STL","STL",...,"MEM","BWI","FLL","STL","MEM"],["CLT","DFW","STL","MEM","MDT",...,"CMH","CVG","LAS","DTW","CVG"],...,["DEN","CRP","STL","DAL","MLU",...,"DTW","PBI","MCO","BWI","BOS"],["PIT","PHL","PWM","PHX","MEM",...,"SAV","BOS","HSV","DEN","DTW"]]
```

</p>
</details>

Admittedly, we'd still need add (if possible) support for duration/timedelta on the `altair`-side:
- https://github.com/vega/altair/blob/a0c091eca897e1b9eaa6bb70d8ae8dc1deff9e60/altair/utils/core.py#L418-L425
- https://github.com/vega/altair/blob/a0c091eca897e1b9eaa6bb70d8ae8dc1deff9e60/altair/utils/core.py#L484-L491

However, the `date` column is supported, fairly cheap and consistently parsed.
That last point is something we've encountered with other datasets (see https://github.com/vega/altair/pull/3631#issuecomment-2480816377)

**Comment by domoritz** [comment]
That would probably be good for the 3m dataset. I'm supportive.
