### ISSUE TITLE
breaking: Rename `weather.json` -> `weekly-weather.json`

### ISSUE THREAD

**Issue by dangotbanned** [vega/vega-datasets#633]
Following #631, I was surprised to find that we have two *very different* datasets named `"weather"`.
I'd expected datasets sharing the same [*base name/stem*](https://en.wikipedia.org/wiki/Filename#Filename_extensions) to represent the same source. 
`"flights-200k"` is the only other duplicated name - but both the `.arrow` and `.json` files represent the same data.

I'm thinking ahead towards (https://github.com/vega/altair/pull/3631#issuecomment-2485922817), where there may be datasets with `.json` and `.parquet` versions.
In that world, a guarantee on a shared *stem* representing the same data would provide options to resolve incompatibilities in (https://github.com/vega/altair/pull/3631#issuecomment-2486370528)

I do understand renaming would have to be a **breaking change**, and should not be taken lightly.

# Usage
The following uses [jsdelivr-stats](https://www.jsdelivr.com/package/npm/vega-datasets?tab=stats) looking at the range of the *past year*.

Currently, [altair-viz/vega_datasets](https://github.com/altair-viz/vega_datasets) is by far the *greatest* source of traffic - which is pinned on [`v1.29.0`](https://github.com/vega/vega-datasets/releases/tag/v1.29.0).

## Versions

| Version   | Requests      |
| --------- | ------------- |
| `v1.29.0` | **6,802,781** |
| `v1.31.1` | 215,574       |
| `v2.7.0`  | 190,102       |

### `v1.29.0`

There is a [`weather.csv`](https://github.com/vega/vega-datasets/blob/v1.29.0/data/weather.csv) for this version - but is not accessible using the `python` api.
[`"weather"`](https://github.com/altair-viz/vega_datasets/blob/136e850447b49031f04baa137ce5c37a6678bbb1/vega_datasets/datasets.json#L258-L261) is defined as a reference to `weather.json` **only**.

The effect this has is quite apparent when comparing the traffic per-file:

| Dataset (`v1.29.0`) | Requests  |
| ------------------- | --------- |
| `movies.json`       | 1,804,118 |
| `population.json`   | 654,426   |
| ...                 | ...       |
| 40 most popular     | 5,000+    |
| `weather.json`      | 2,154     |
| `weather.csv`       | **31**    |

Given that `v1.29.0` is [baked into](https://github.com/altair-viz/vega_datasets/blob/136e850447b49031f04baa137ce5c37a6678bbb1/vega_datasets/core.py#L10-L12) the package - none of this usage would be impacted by the change.

[jsdelivr-npm](https://www.jsdelivr.com/documentation#id-npm) seems to be able to handle version-fallback in the event that anyone is using `@latest` - so maybe the impact of this change is fairly limited?

# Descriptions

<details><summary><code>weather.json</code></summary>
<p>

https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/SOURCES.md#L403-L405
https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/datapackage.json#L1207-L1215

</p>
</details> 

<details><summary><code>weather.csv</code></summary>
<p>

https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/SOURCES.md#L407-L409
https://github.com/vega/vega-datasets/blob/719c388cc844392cda24517e4e0cda976b1d8519/datapackage.json#L1679-L1718

</p>
</details> 

#### Side note
Having a unique [`name`](https://specs.frictionlessdata.io/data-resource/#name) per-[resource](https://specs.frictionlessdata.io/data-resource/) is part of the spec we haven't met yet.
I'm less interested in that part as we can just include the suffix if needed.

**Comment by dsmedia** [comment]
Just for context on the spec itself, below is the language from datapackage.org, which advises against, but doesn't appear to preclude, a resource name differing from its filename (ex-extension). It sounds like a good practice to keep the filename roots distinct, which would have to be weighed against the cost of a breaking change to an existing filename. Probably a call for @domoritz . 

A resource MUST contain a name property. The name is a simple name or identifier to be used for this resource.

It MUST be unique amongst all resources in this data package.

It SHOULD be human-readable and consist only of lowercase English alphanumeric characters plus ., - and _.

It would be usual for the name to correspond to the file name (minus the extension) of the data file the resource describes.

**Comment by domoritz** [comment]
I think we can rename but should do a major version bump of it's not backwards compatible. I'm okay with doing that alongside moving to esm for example.

**Comment by dsmedia** [comment]
[@dangotbanned wrote](https://github.com/vega/vega-datasets/issues/633#issue-2703143316):

> "flights-200k" is the only other duplicated name - but both the .arrow and .json files represent the same data.
> #### Side note
> Having a unique [`name`](https://specs.frictionlessdata.io/data-resource/#name) per-[resource](https://specs.frictionlessdata.io/data-resource/) is part of the spec we haven't met yet. I'm less interested in that part as we can just include the suffix if needed.

It does seem like a limitation of Frictionless Data to not accommodate multiple file formats of the same underlying dataset under a single logical [`name`](https://specs.frictionlessdata.io/data-resource/#name). Perhaps the Frictionless Data specification maintainers will address this use case in a future version. 

For now, though, since we're already going to introduce a breaking change to resolve `weather`, should we bite the bullet and resolve the name conflict for `flights-200k`, the only remaining spec-breaking duplicate name, in order to be compliant with the Frictionless spec? 

We could follow a simple priority rule where the JSON version keeps the base name `flights-200k` while the Arrow version becomes `flights-200k-arrow`, following a general precedence of, perhaps, CSV > JSON > Parquet > Arrow for base names. This would:

- Keep the most human-readable format as the default name
- Only add format suffixes when needed to resolve conflicts
- Achieve full spec compliance with minimal renaming

Would it make sense to handle both naming conflicts in a single breaking change?

**Comment by domoritz** [comment]
Yeah, single breaking change. 

We should raise an issue with the frictionless data group that we can follow to update here when it's out.

**Comment by dangotbanned** [comment]
> We could follow a simple priority rule where the JSON version keeps the base name flights-200k while the Arrow version becomes flights-200k-arrow, following a general precedence of, perhaps, CSV > JSON > Parquet > Arrow for base names.

@dsmedia I realise I didn't explain why I suggested `weather.csv` should be renamed but `weather.json` should not.
[weather.json](https://github.com/vega/vega-datasets/commits/main/data/weather.json) was added 2 years prior to [weather.csv](https://github.com/vega/vega-datasets/commits/main/data/weather.csv
)

Could you explain the reasoning for `flights-200k-arrow` vs `flights-200k.arrow`?
Both seems to allowed per the definition of [`name`](https://specs.frictionlessdata.io/data-resource/#name), but the former introduces a **fourth** way to identify a `arrow` resource.

We can currently use:
1. `path`
2. `format`
3. `mediatype`

https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/datapackage.json#L628-L634

---

As an aside, I've got some local changes to (https://github.com/vega/altair/pull/3631) that are utilizing `datapackage.json` already.
For that, I'm exclusively using `path` to extract the name as there is another minor issue that `name` must be lowercase:

> It MUST consist only of lowercase alphanumeric characters plus “.”, “-” and “_”.

I don't think that is an issue for the URL, but there are some *camelCase* names I'd preserved in their `python` representation:

https://github.com/vega/altair/blob/a982759715061c436ea93aea8234cd04dfca4657/altair/datasets/_typing.py#L72-L74

**Comment by dsmedia** [comment]
My concern is only with the non-unique `"name"` appearing twice in the resources portion of the json. (The filenames themselves are fine in this case.)

https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/datapackage.json#L597-L599

https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/datapackage.json#L627-L629

Here is the relevant json spec:
[name [required]](https://datapackage.org/standard/data-resource/#name)
> A resource MUST contain a name property. The name is a simple name or identifier to be used for this resource.
> **It MUST be unique amongst all resources in this data package.** 

My suggestion above was just for how the script would be designed to avoid duplicate Resources names.

**Comment by dangotbanned** [comment]
(https://github.com/vega/vega-datasets/issues/633#issuecomment-2513298738)

@dsmedia I'm going to try and illustrate the issues I have a little better.

This is how each form is interpreted by [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html)

```py
from pathlib import Path

CURRENT = "flights-200k"
DOT = "flights-200k.arrow" # (https://github.com/vega/vega-datasets/issues/633#issuecomment-2511517256)
HYPHEN = "flights-200k-arrow" # (https://github.com/vega/vega-datasets/issues/633#issuecomment-2511334248)

>>> Path(CURRENT).name, Path(DOT).name, Path(HYPHEN).name
('flights-200k', 'flights-200k.arrow', 'flights-200k-arrow')

>>> Path(CURRENT).stem, Path(DOT).stem, Path(HYPHEN).stem
('flights-200k', 'flights-200k', 'flights-200k-arrow')

>>> Path(CURRENT).suffix, Path(DOT).suffix, Path(HYPHEN).suffix
('', '.arrow', '')
```

The first problem is that using a `-` breaks these basic splitting operations.
By using a `.` we can very easily detect representations of the same dataset:

```py
>>> Path("flights-200k.json").stem == Path("flights-200k.arrow").stem
True
```

The second issue relates to:
> We could follow a simple priority rule where the **JSON** version keeps the base name **flights-200k** while the Arrow version becomes **flights-200k-arrow**
> following a general precedence of, perhaps, CSV > JSON > Parquet > Arrow for base names.

> [!IMPORTANT]
> I'd consider this is a [leaky abstraction](https://en.wikipedia.org/wiki/Leaky_abstraction)

If one wants to use the `name` for anything, they need to check:
1. Does the name contain any `-`?
	- Remember that `-` *could* be part of the actual file name
2. Does the final segment (`"seg1-seg2-seg3"`) match one of these established suffixes?
	- Are there any new suffixes since last checking?
	- Has the precedence changed?
3. Are there any other names with a similar prefix?


The additional complexity wouldn't be something I'd want to model in ([altair#3631/commits/909e7d0](https://github.com/vega/altair/pull/3631/commits/909e7d05e57718b2f634a7e6781cb4e58a835837#diff-6db8d2c117b604b1ec59a006ab56a8587dfc343bdfd46b5f4778dc24264fdfff)). 
I would continue using `path` as I could more reliably derive the name and detect collisions.
There would be no need to concern myself with how `vega-datasets` prioritizes naming conventions.

---


> My suggestion above was just for how the script would be designed to avoid duplicate Resources names.

For this *specific case*, we'd only need to make the following change:

```diff
diff --git a/datapackage.json b/datapackage.json
index 2105719..4158b86 100644
--- a/datapackage.json
+++ b/datapackage.json
@@ -625,7 +625,7 @@
       }
     },
     {
-      "name": "flights-200k",
+      "name": "flights-200k.arrow",
       "type": "table",
       "path": "flights-200k.arrow",
       "scheme": "file",
diff --git a/scripts/build_datapackage.py b/scripts/build_datapackage.py
index 30834a6..ffb7661 100755
--- a/scripts/build_datapackage.py
+++ b/scripts/build_datapackage.py
@@ -188,7 +188,7 @@ class ResourceAdapter:
     def _extract_file_parts(cls, source: Path, /) -> dict[PathMeta, str]:
         """Metadata that can be inferred from the file path *alone*."""
         parts = {
-            "name": source.stem,
+            "name": source.name,
             "path": source.name,
             "format": source.suffix[1:],
             "scheme": "file",
```

A more generalized solution (doing this for formats other than `arrow`) would look a little different.
Something like:
1. Check for duplicated [`Path.stem`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem) upfront
2. In those cases, use [`Path.name`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name) (include the suffix)

Although, I think it would be simpler to just use [`Path.name`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name) in **all cases** - regardless of duplicates.

We already have the guarantee of [**uniqueness**](https://en.wikipedia.org/wiki/Filename#Uniqueness) provided by the filesystem.
Adding or removing alternate formats will not impact the name of an existing file

**Comment by domoritz** [comment]
The issue for doing major version bumps: https://github.com/vega/vega/issues/3990. I'm planning to get to this over the winter break. We can include breaking changes from file renaming etc as well so let me know what you decide makes the most sense.

**Comment by dsmedia** [comment]
@dangotbanned This sounds quite reasonable: "Path.name in all cases - regardless of duplicates." The filesystem-based uniqueness guarantee is ideal. Thanks!

**Comment by dangotbanned** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/125183946?s=64&amp;v=4">@dangotbanned](https://github.com/dangotbanned) This sounds quite reasonable: "Path.name in all cases - regardless of duplicates." The filesystem-based uniqueness guarantee is ideal. Thanks!

Great, thanks for understanding @dsmedia

What do you think about splitting (https://github.com/vega/vega-datasets/issues/633#issuecomment-2514551722) into another issue, and handling that after this one?

Both are tackling naming issues, but the changes are quite different:
- `weather.csv` will actually rename a file (*I have no preference on what that should be*), making changes to
	- [/data/weather.csv](https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/data/weather.csv)
	- [/src/urls.ts](https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/src/urls.ts)
	- [/SOURCES.md](https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/SOURCES.md)
- the `Resource.name` part is scoped to changes in
	- [/datapackage.json](https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/datapackage.json)
	- [/scripts/build_datapackage.py](https://github.com/vega/vega-datasets/blob/8745f5c61ba951fe057a42562b8b88604b4a3735/scripts/build_datapackage.py)

**Comment by dsmedia** [comment]
> What do you think about splitting (https://github.com/vega/vega-datasets/issues/633#issuecomment-2514551722) into another issue, and handling that after this one?

100% - it makes sense to split into a separate issue. 

> weather.csv will actually rename a file (I have no preference on what that should be), making changes to

As for the naming, since `weather.csv` is a superset of `seattle-weather.csv` (see verification script below), with the additon of a location field and New York data, perhaps the most logical name would be `seattle-newyork-weather.csv` or `city-weather.csv`. The former is more descriptive and consistent with the naming of co-dataset `seattle-weather.csv` but the latter is more concise. 

Also, as part of this issue, If the generation script adds some constraints on naming any future datasets (or if there are guidelines that future dataset authors should follow for naming), should these constraints/guidelines be documented somewhere in this repo?

Separately, I'm not familiar with the norms around breaking changes, but what efforts can or should be made to alert / repair sites that depend on the weather.csv file, e.g. [this](https://www.queryverse.org/VegaLite.jl/v2.1/examples/examples_repeat_concatenation/) and [this](https://kapitan.net/data-viz-course/docs/altair_view_composition.html)?

<details>
<summary>Script checking if `seattle-weather.csv` is a subset of `weather.csv`</summary>

```python
import pandas as pd

# Load the datasets from raw GitHub URLs
seattle_url = "https://raw.githubusercontent.com/vega/vega-datasets/main/data/seattle-weather.csv"
weather_url = "https://raw.githubusercontent.com/vega/vega-datasets/main/data/weather.csv"

# Read the datasets
seattle_df = pd.read_csv(seattle_url)
weather_df = pd.read_csv(weather_url)

# Filter weather dataset for Seattle
seattle_in_weather = weather_df[weather_df['location'] == 'Seattle'].drop('location', axis=1)

def compare_datasets(seattle_specific, seattle_in_weather):
    print("Basic information:")
    print(f"Seattle-specific dataset shape: {seattle_specific.shape}")
    print(f"Seattle records in weather dataset shape: {seattle_in_weather.shape}")
    
    # Compare columns
    print("\nColumns in seattle-weather.csv:", seattle_specific.columns.tolist())
    print("Columns in weather.csv (Seattle records, after dropping location):", 
          seattle_in_weather.columns.tolist())
    
    # Sort both datasets by date for proper comparison
    seattle_specific['date'] = pd.to_datetime(seattle_specific['date'])
    seattle_in_weather['date'] = pd.to_datetime(seattle_in_weather['date'])
    
    seattle_specific_sorted = seattle_specific.sort_values('date').reset_index(drop=True)
    seattle_in_weather_sorted = seattle_in_weather.sort_values('date').reset_index(drop=True)
    
    # Compare date ranges
    print("\nDate ranges:")
    print(f"Seattle-specific dataset: {seattle_specific['date'].min()} to {seattle_specific['date'].max()}")
    print(f"Weather dataset (Seattle): {seattle_in_weather['date'].min()} to {seattle_in_weather['date'].max()}")
    
    # Check if datasets are identical after sorting
    is_identical = seattle_specific_sorted.equals(seattle_in_weather_sorted)
    print(f"\nAre the datasets identical? {is_identical}")

# Run the comparison
compare_datasets(seattle_df, seattle_in_weather)
```
</details>

**Results:**
```
Basic information:
Seattle-specific dataset shape: (1461, 6)
Seattle records in weather dataset shape: (1461, 6)

Columns in seattle-weather.csv: ['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather']
Columns in weather.csv (Seattle records, after dropping location): ['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather']

Date ranges:
Seattle-specific dataset: 2012-01-01 00:00:00 to 2015-12-31 00:00:00
Weather dataset (Seattle): 2012-01-01 00:00:00 to 2015-12-31 00:00:00

Are the datasets identical? True
```

**Comment by domoritz** [comment]
weather.csv may be used a lot more than weather.json, though. The latter is really only used in https://vega.github.io/vega/examples/weekly-temperature/. This shows up for example at https://www.jsdelivr.com/package/npm/vega-datasets?tab=files&path=data&version=2.9.0. ![Image](https://github.com/user-attachments/assets/a17033ca-61cc-445a-8e62-0036198b63b7)

We may want to leave weather.csv and rename the json one if needed.

I just thought of this.

**Comment by dangotbanned** [comment]
> As for the naming, since `weather.csv` is a superset of `seattle-weather.csv` (see verification script below), with the additon of a location field and New York data, perhaps the most logical name would be `seattle-newyork-weather.csv` or `city-weather.csv`. The former is more descriptive and consistent with the naming of co-dataset `seattle-weather.csv` but the latter is more concise.

Well spotted on identifying the link between the two datasets @dsmedia 

I'd say we're in an unfortunate situation here.
If we were starting fresh (and `weather.json` didn't exist), I'd say:
- `weather.csv` -> `weather.csv`
- `seattle-weather.csv` -> `weather-seattle.csv`

But that introduces a change elsewhere and IIRC `weather-seattle.csv` is used quite frequently

**Comment by dangotbanned** [comment]
> Separately, I'm not familiar with the norms around breaking changes, but what efforts can or should be made to alert / repair sites that depend on the weather.csv file, e.g. [this](https://www.queryverse.org/VegaLite.jl/v2.1/examples/examples_repeat_concatenation/) and [this](https://kapitan.net/data-viz-course/docs/altair_view_composition.html)?

@dsmedia 
It really depends on how they've integrated with this repo, the point I made in [description] is related:

> > Given that `v1.29.0` is [baked into](https://github.com/altair-viz/vega_datasets/blob/136e850447b49031f04baa137ce5c37a6678bbb1/vega_datasets/core.py#L10-L12) the package - none of this usage would be impacted by the change.
> 
> [jsdelivr-npm](https://www.jsdelivr.com/documentation#id-npm) seems to be able to handle version-fallback in the event that anyone is using `@latest` - so maybe the impact of this change is fairly limited?

**Comment by dangotbanned** [comment]
> weather.csv may be used a lot more than weather.json, though. The latter is really only used in [vega.github.io/vega/examples/weekly-temperature](https://vega.github.io/vega/examples/weekly-temperature/). This shows up for example at [jsdelivr.com/package/npm/vega-datasets?tab=files&path=data&version=2.9.0](https://www.jsdelivr.com/package/npm/vega-datasets?tab=files&path=data&version=2.9.0). ![Image](https://github.com/user-attachments/assets/a17033ca-61cc-445a-8e62-0036198b63b7)
> 
> We may want to leave weather.csv and rename the json one if needed.
> 
> I just thought of this.

@domoritz yeah I think that's fair - `weather.json` usage seems to only be higher on [`1.29.0`](https://www.jsdelivr.com/package/npm/vega-datasets?tab=files&path=data&version=1.29.0)

With [altair-viz/vega_datasets](https://github.com/altair-viz/vega_datasets) being unmaintained, it makes more sense to prioritize use cases that may actually break

**Comment by domoritz** [comment]
Do we still need to rename after we change how we generate names for the data package?

**Comment by dangotbanned** [comment]
> Do we still need to rename after we change how we generate names for the data package?

Yeah I think so @domoritz 
My original issue was this concern:

> Following [#631](https://github.com/vega/vega-datasets/pull/631), I was surprised to find that we have two _very different_ datasets named `"weather"`. I'd expected datasets sharing the same [_base name/stem_](https://en.wikipedia.org/wiki/Filename#Filename_extensions) to represent the same source. `"flights-200k"` is the only other duplicated name - but both the `.arrow` and `.json` files represent the same data.
> 
> I'm thinking ahead towards ([vega/altair#3631 (comment)](https://github.com/vega/altair/pull/3631#issuecomment-2485922817)), where there may be datasets with `.json` and `.parquet` versions. In that world, a guarantee on a shared _stem_ representing the same data would provide options to resolve incompatibilities in ([vega/altair#3631 (comment)](https://github.com/vega/altair/pull/3631#issuecomment-2486370528))

Regardless of the unique full file names, if we created `weather.parquet` what would that refer to?

**Comment by domoritz** [comment]
That's a good suggestion. I think we should do that.
