### ISSUE TITLE
Configure and run `taplo` in CI for formatting `.toml`

### ISSUE THREAD

**Issue by dangotbanned** [vega/vega-datasets#646]
_Originally posted by @dangotbanned in https://github.com/vega/vega-datasets/pull/643#discussion_r1879972721_

I should've explained this better in the description for (https://github.com/vega/vega-datasets/pull/643/commits/1ea28125fc3e0a0e3973edef04f92866b4b27ed6)

That commit uses [automatic formatting](https://taplo.tamasfe.dev/configuration/formatter-options.html) via [`taplo`](https://taplo.tamasfe.dev/).
The two non-default configuration options applied were:

`align_entries=true`
> Align entries vertically. Entries that have table headers, comments, or blank lines between them are not aligned.

`allowed_blank_lines=1`
> The maximum amount of consecutive blank lines allowed.

---

`taplo` can be used via its [CLI](https://taplo.tamasfe.dev/cli/introduction.html) and as a VSCode extension ([Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml))

I haven't used it in CI before, but it is [available on `PyPI`](https://pypi.org/project/taplo) - so we could run it with `uvx`?
https://github.com/tamasfe/taplo/blob/a8bc571ee28775e7d5ad84c2ea87cf5b61ab42f5/.github/workflows/releases.yaml#L503-L504

[NPM](https://taplo.tamasfe.dev/cli/installation/npm.html) is another option for install

---

@domoritz
> If we have a formatter, it should run on the ci as well.

**Comment by domoritz** [comment]
I haven't heard of it but sounds good. I'd recommend uvx since it's for python.

**Comment by dangotbanned** [comment]
> I haven't heard of it but sounds good. I'd recommend uvx since it's for python.

Great, that sounds like something I can take a stab at

@domoritz would it be worth opening a separate issue for a `pyproject.toml`?

I've been using one locally for [`ruff`](https://github.com/astral-sh/ruff) & [`pyright`](https://github.com/microsoft/pyright) e.g. (https://github.com/vega/vega-datasets/pull/645/commits/2b1be705fef15899a51155573ba5c42f4febf2d9), (https://github.com/vega/vega-datasets/pull/643/commits/fbd1be573bb3257d5f1e2eb643b1bd97d6acf380), (https://github.com/vega/vega-datasets/pull/640/commits/5e779e6a353833fd4ea11658be1573a808ec77bc)
It would probably be easier to manage `uv` as a project, and naturally provides a home for other tool configs
