### ISSUE TITLE
Updated Arrow files unreadable by JS libs

### ISSUE THREAD

**Issue by jheer** [vega/vega-datasets#655]
It looks like recent changes to `flights-200k.arrow` include compression. Unfortunately compressed data is not supported by either the Apache Arrow JS lib or Flechette. I recommed reverting to uncompressed data.

Here are the results of trying to load the file with both libraries within an Observable notebook:

<img width="639" alt="Image" src="https://github.com/user-attachments/assets/4dcdeea5-302d-4132-ba71-839cfa7c21f4" />

(Originally raised in [@uwdata/flechette#26](https://github.com/uwdata/flechette/issues/26))

**Comment by dangotbanned** [comment]
Sorry to have broken this for you @jheer!

https://github.com/vega/vega-datasets/blob/369b462f7505e4ef3454668793e001e3620861ff/scripts/flights.py#L503-L504

Just to confirm, from the options in [`polars.dataframe.write_ipc`](https://docs.pola.rs/api/python/stable/reference/api/polars.DataFrame.write_ipc.html#polars-dataframe-write-ipc); only `"uncompressed"` is expected to work for you?

I think I was concerned about the significant [size difference in `flights-3m`](https://github.com/vega/vega-datasets/issues/627#issuecomment-2474228235) when I chose that option.
But any reduction in size is useless if you can't read it anyway :sweat_smile:

We should definitely fix this before #654

**Comment by domoritz** [comment]
The 3m is less of a concern but we should not compress the 200k arrow file.
